import { Consultation, PageShell } from "../components";

export default function Materials(){return <PageShell>
  <section className="material-hero"><div><p className="breadcrumbs"><a href="/">Trang chủ</a> / Vật liệu PIMA</p><p className="eyebrow">Nền tảng của nội thất bền</p><h1>Tấm nhựa PIMA cho<br /><em>nội thất hiện đại</em></h1><p>Vật liệu dạng tấm được phát triển cho gia công nội thất, hỗ trợ đa dạng ứng dụng từ khu vực khô đến khu vực thường xuyên có độ ẩm.</p><a className="button primary" href="#tu-van">Nhận mẫu & tư vấn <span>↗</span></a></div><img src="/images/material-boards.webp" alt="Các lớp tấm nhựa PIMA và bề mặt hoàn thiện"/></section>
  <section className="material-proof"><p className="eyebrow">Lợi ích cốt lõi</p><div className="proof-grid"><article><b>01</b><h2>Kháng ẩm</h2><p>Cốt vật liệu nhựa phù hợp với điều kiện nóng ẩm và các khu vực có nguy cơ tiếp xúc nước.</p></article><article><b>02</b><h2>Không mối mọt</h2><p>Giúp giảm nỗi lo côn trùng phá hại thường gặp ở vật liệu nội thất truyền thống.</p></article><article><b>03</b><h2>Dễ gia công</h2><p>Có thể cắt, khoan, bắt vít và hoàn thiện thành nhiều sản phẩm theo bản vẽ.</p></article><article><b>04</b><h2>Đa dạng bề mặt</h2><p>Phối hợp film, laminate, acrylic và các bề mặt trang trí tùy cấu hình sản phẩm.</p></article></div></section>
  <section className="application-table"><div><p className="eyebrow light">Gợi ý ứng dụng</p><h2>Chọn vật liệu theo<br />đúng điều kiện sử dụng</h2></div><div className="table-wrap"><div><b>Không gian</b><b>Ứng dụng</b><b>Lưu ý</b></div><div><span>Bếp</span><span>Thùng tủ, cánh, tủ kho</span><span>Tính tải trọng và vị trí thiết bị</span></div><div><span>Phòng ngủ</span><span>Tủ áo, bàn, kệ</span><span>Tối ưu nhịp kệ và phụ kiện</span></div><div><span>Phòng tắm</span><span>Tủ lavabo, tủ gương</span><span>Khảo sát đường ống và kết cấu treo</span></div><div><span>Phòng khách</span><span>Kệ TV, vách, tủ giày</span><span>Gia cường vị trí tải trọng lớn</span></div></div></section>
  <section className="care-section"><div><p className="eyebrow">Sử dụng & bảo quản</p><h2>Để sản phẩm<br /><em>bền đẹp lâu dài</em></h2></div><ul><li>Lắp đặt trên bề mặt phẳng, liên kết đúng kỹ thuật.</li><li>Chọn phụ kiện và vít phù hợp với cấu tạo sản phẩm.</li><li>Lau sạch bằng khăn mềm; tránh hóa chất có tính ăn mòn mạnh.</li><li>Không đặt nguồn nhiệt cao tiếp xúc trực tiếp với bề mặt.</li><li>Bảo quản tấm nằm phẳng, kê đỡ đều và tránh nắng mưa trực tiếp.</li></ul></section>
  <Consultation title="Bạn cần chọn loại tấm phù hợp?" />
  </PageShell>}
