import { Consultation, PageShell } from "../components";

export default function Partners(){return <PageShell>
  <section className="partner-hero"><div><p className="breadcrumbs"><a href="/">Trang chủ</a> / Dành cho đối tác</p><p className="eyebrow">Đồng hành cùng PIMA</p><h1>Chủ động nguồn tấm.<br /><em>Mở rộng năng lực.</em></h1><p>Giải pháp dành cho xưởng nội thất, đơn vị thiết kế – thi công, đại lý, OEM và dự án cần nguồn vật liệu ổn định cùng hỗ trợ kỹ thuật.</p><a className="button primary" href="#tu-van">Đăng ký hợp tác <span>↗</span></a></div><img src="/images/workshop.webp" alt="Xưởng gia công nội thất từ tấm nhựa PIMA"/></section>
  <section className="partner-types"><p className="eyebrow">Phù hợp với mô hình của bạn</p><div><article><span>01</span><h2>Xưởng nội thất</h2><p>Nhập tấm về gia công tủ bếp, tủ áo, lavabo, kệ và sản phẩm theo đơn hàng.</p></article><article><span>02</span><h2>Đơn vị thi công</h2><p>Được tư vấn cấu hình vật liệu theo không gian, công năng và yêu cầu dự án.</p></article><article><span>03</span><h2>Đại lý & OEM</h2><p>Phát triển danh mục riêng, chính sách theo sản lượng và hỗ trợ mẫu bán hàng.</p></article></div></section>
  <section className="support-system"><div><p className="eyebrow light">Hệ thống hỗ trợ</p><h2>Không chỉ cung cấp tấm.<br /><em>Cùng giải bài toán đầu ra.</em></h2></div><div className="support-list"><article><b>01</b><h3>Tư vấn sản phẩm</h3><p>Gợi ý loại tấm, độ dày và bề mặt theo ứng dụng.</p></article><article><b>02</b><h3>Mẫu & tài liệu</h3><p>Hỗ trợ mẫu vật liệu và nội dung phục vụ tư vấn khách hàng.</p></article><article><b>03</b><h3>Kỹ thuật gia công</h3><p>Trao đổi nguyên tắc cắt, dán, liên kết và bảo quản.</p></article><article><b>04</b><h3>Chính sách sản lượng</h3><p>Xây dựng phương án theo nhóm khách hàng và quy mô đơn hàng.</p></article></div></section>
  <section className="partner-steps"><p className="eyebrow">Quy trình hợp tác</p><ol><li><span>01</span><h3>Trao đổi nhu cầu</h3><p>Sản phẩm, thị trường, sản lượng và phương thức hợp tác.</p></li><li><span>02</span><h3>Gửi mẫu – báo giá</h3><p>Chốt cấu hình, mẫu màu và điều kiện thương mại.</p></li><li><span>03</span><h3>Đơn hàng thử</h3><p>Kiểm chứng khả năng gia công và phản hồi thị trường.</p></li><li><span>04</span><h3>Mở rộng lâu dài</h3><p>Chuẩn hóa danh mục và kế hoạch sản lượng định kỳ.</p></li></ol></section>
  <Consultation title="Trao đổi cơ hội hợp tác cùng PIMA" />
  </PageShell>}
